### ISSUE TITLE
Selecting RTL-SDR TCP causes a crash

### ISSUE THREAD

**Issue by lmore377** [lutusp/PLSDR#2]
There's not much else to say. other than i have to manually kill it. I haven't tested with the SDR connected directly to my computer, but I will try it later

This is the console output after i select TCP

lauro@ubuntu:~/Desktop/PLSDR$ ./PLSDR.py 

gr-osmosdr v0.1.x-xxx-xunknown (0.1.5git) gnuradio 3.7.11
built-in source types: file osmosdr fcd rtl rtl_tcp plutosdr miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya 

FATAL: Failed to open AirSpy device (-5) AIRSPY_ERROR_NOT_FOUND

Trying to fill up 1 missing channel(s) with null source(s).
This is being done to prevent the application from crashing
due to gnuradio bug #528.

gr-osmosdr v0.1.x-xxx-xunknown (0.1.5git) gnuradio 3.7.11
built-in source types: file osmosdr fcd rtl rtl_tcp plutosdr miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya

**Comment by lutusp** [comment]
> There's not much else to say.

On the contrary. On starting up, my program tried to find the default device based on alphabetical order (an Airspy), then printed an error message when it couldn't, and there was no crash (an error message is not a crash). This is normal behavior. Your next step is to connect a radio device, then select it in the device selection drop-down list.

The reason for this behavior is that GnuRadio's errors cannot be trapped and managed, they can only be printed. This is why running PLSDR in a command shell is so useful.


> other than i have to manually kill it. 

You left out the step where you tried to select your radio device after connecting the device to the computer. Assuming you did that.

As to enabling an RTL-SDR TCP device (from your title), you need to edit my program's radio list, as explained in [the documentation](https://arachnoid.com/PLSDR/), to include the specific IP and port you've configured for your device.

In the file PLSDR.py, starting on line 68, is a list of radio names and invocation strings. Your device's invocation string is located on line 80 in the current version. You will notice on line 80 the comment "change this IP:port value", since my program cannot know in advance which IP or port you chose for your device.

Please tell me if this solves your issue.

**Comment by lmore377** [comment]
Forgot to read the docs.

**Comment by lutusp** [comment]
> Forgot to read the docs.

No problem. But could you please tell me what IP and port setting worked for you?I ask because if they're generic settings (like 127.0.0.1:some port), I can add them to my program so the next person who tries to connect using your device make and model won't experience the same frustration.

Thanks!

**Comment by lmore377** [comment]
Actually I had rtl_tcp running on a separate computer so it was just a different ip.

**Comment by lutusp** [comment]
> Actually I had rtl_tcp running on a separate computer so it was just a different ip.

Okay, so can you tell me whether you're up and running with PLSDR, and whether I should make any changes in the default entry for your device? Like a default port that the manufacturer assumes is in force?

Thanks!
